ALTER TABLE npcs
  ADD COLUMN IF NOT EXISTS misc               JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS reactions          JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS bonus_actions      JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS legendary_actions  JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS lair_actions       JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS regional_effects   JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS mythic_actions     JSONB NOT NULL DEFAULT '[]';
