ALTER TABLE characters
  ADD COLUMN subclass  TEXT NOT NULL DEFAULT '',
  ADD COLUMN subrace   TEXT NOT NULL DEFAULT '',
  ADD COLUMN temp_hp   INT  NOT NULL DEFAULT 0,
  ADD COLUMN inventory TEXT NOT NULL DEFAULT '';
